In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns; sns.set()
from scipy.spatial.distance import cdist
import random 

np.random.seed(11)

In [2]:
means = [[2, 2], 
         [8, 3], 
         [3, 6]]
cov = [[1, 0], 
       [0, 1]]

N = 5     # số điểm DL 

X0 = np.random.multivariate_normal(means[0], cov, N)  # sinh N điểm DL hai chiều (MT N x 2)
X1 = np.random.multivariate_normal(means[1], cov, N)  # sinh N điểm DL hai chiều (MT N x 2)
X2 = np.random.multivariate_normal(means[2], cov, N)  # sinh N điểm DL hai chiều (MT N x 2)

X = np.concatenate((X0, X1, X2), axis = 0)    # tạo ma trận đặc trưng (nối theo chiều dọc) (MT 3N x 2)

In [3]:
X    # ma trận 15 x 2 

array([[ 3.74945474,  1.713927  ],
       [ 1.51543487, -0.65331856],
       [ 1.99171537,  1.68036864],
       [ 1.46337064,  2.31540267],
       [ 2.42105072,  0.93439702],
       [ 7.11376033,  2.52426651],
       [ 8.68968231,  3.56119218],
       [ 6.69445149,  1.88052474],
       [ 8.73683739,  4.57463407],
       [ 7.96892491,  2.31655337],
       [ 4.0956297 ,  5.69042336],
       [ 3.72575222,  7.54907163],
       [ 3.63007982,  6.07349324],
       [ 3.73227135,  5.35742461],
       [ 2.82190682,  5.42604544]])

In [9]:
k = 3   # 3 clusters 
original_label = np.asarray([0]*N + [1]*N + [2]*N).T     # list concatenation (row vector)

In [5]:
original_label

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [6]:
original_label == 0 

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [7]:
original_label == 1

array([False, False, False, False, False,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [14]:
centroids = X[np.random.choice(X.shape[0], size = k, replace = False)]

In [15]:
centroids

array([[1.46337064, 2.31540267],
       [3.73227135, 5.35742461],
       [3.74945474, 1.713927  ]])

In [16]:
cdist(X, centroids)

array([[2.36388526, 3.64353812, 0.        ],
       [2.96917773, 6.40651211, 3.25494952],
       [0.82608497, 4.06820301, 1.75805969],
       [0.        , 3.7949714 , 2.36388526],
       [1.68057363, 4.61329303, 1.54023513],
       [5.65424865, 4.41149096, 3.46052051],
       [7.33291019, 5.27279569, 5.27429967],
       [5.24912618, 4.56764095, 2.94970518],
       [7.61626189, 5.0654163 , 5.74957656],
       [6.50555438, 5.21499101, 4.2622866 ],
       [4.28013463, 0.49286657, 3.9915361 ],
       [5.70172441, 2.19165672, 5.83519277],
       [4.33795729, 0.72332385, 4.36120031],
       [3.7949714 , 0.        , 3.64353812],
       [3.39436578, 0.91294709, 3.8262473 ]])

np.amax(): Return the maximum of an array or maximum along an axis

In [17]:
X0

array([[ 3.74945474,  1.713927  ],
       [ 1.51543487, -0.65331856],
       [ 1.99171537,  1.68036864],
       [ 1.46337064,  2.31540267],
       [ 2.42105072,  0.93439702]])

In [19]:
np.amax(X0)    # tìm max của tất cả các phần tử của ma trận 

3.749454741305179

In [20]:
np.amax(X0, axis = 0)    # tìm max của từng cột 

array([3.74945474, 2.31540267])

In [21]:
np.amax(X0, axis = 1)    # tìm max của từng hàng 

array([3.74945474, 1.51543487, 1.99171537, 2.31540267, 2.42105072])

np.argmin(): Returns the indices of the minimum values along an axis

In [23]:
X0

array([[ 3.74945474,  1.713927  ],
       [ 1.51543487, -0.65331856],
       [ 1.99171537,  1.68036864],
       [ 1.46337064,  2.31540267],
       [ 2.42105072,  0.93439702]])

In [22]:
np.argmin(X0, axis = 1)   # tìm index min của từng hàng 

array([1, 1, 1, 0, 1], dtype=int64)

In [24]:
np.argmin(X0, axis = 0)   # tìm index min của từng cột 

array([3, 1], dtype=int64)

In [25]:
centroids 

array([[1.46337064, 2.31540267],
       [3.73227135, 5.35742461],
       [3.74945474, 1.713927  ]])

In [26]:
set([tuple(a) for a in centroids])

{(1.46337063776527, 2.3154026684256968),
 (3.732271353885255, 5.357424607566646),
 (3.749454741305179, 1.7139270031837057)}

In [28]:
X[original_label == 0, :]

array([[ 3.74945474,  1.713927  ],
       [ 1.51543487, -0.65331856],
       [ 1.99171537,  1.68036864],
       [ 1.46337064,  2.31540267],
       [ 2.42105072,  0.93439702]])

In [29]:
X

array([[ 3.74945474,  1.713927  ],
       [ 1.51543487, -0.65331856],
       [ 1.99171537,  1.68036864],
       [ 1.46337064,  2.31540267],
       [ 2.42105072,  0.93439702],
       [ 7.11376033,  2.52426651],
       [ 8.68968231,  3.56119218],
       [ 6.69445149,  1.88052474],
       [ 8.73683739,  4.57463407],
       [ 7.96892491,  2.31655337],
       [ 4.0956297 ,  5.69042336],
       [ 3.72575222,  7.54907163],
       [ 3.63007982,  6.07349324],
       [ 3.73227135,  5.35742461],
       [ 2.82190682,  5.42604544]])

In [30]:
np.mean(X, axis = 0)    

array([4.55668818, 3.39629373])

In [31]:
centroids

array([[1.46337064, 2.31540267],
       [3.73227135, 5.35742461],
       [3.74945474, 1.713927  ]])

In [32]:
centroids[-1]

array([3.74945474, 1.713927  ])